# PARTE 1

# Series
1. Crea una Serie llamada s con los siguientes valores: 10, 20, 30, 40, 50.
2. Imprime la Serie s.
3. Accede al tercer elemento de la Serie s.
4. Modifica el segundo elemento de la Serie s para que sea 25.
5. Calcula la suma de todos los elementos en la Serie s.
6. Elimina el elemento 50.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Crear una Serie llamada s con los siguientes valores: 10, 20, 30, 40, 50.
s = pd.Series([10, 20, 30, 40, 50])

# Imprime la Serie s.
print("Serie s:", s, sep= "\n")

# Accede al tercer elemento de la Serie s.
print("\nEl tercer elemento de la serie es:", s[2])

# Modifica el segundo elemento de la Serie s para que sea 25.
s[1] = 25

# Calcula la suma de todos los elementos en la Serie s.
print("La suma de todos los elementos de la serie es:", s.sum())

# Elimina el elemento 50.
del s[4]

print("\nSerie s:", s, sep= "\n")

Serie s:
0    10
1    20
2    30
3    40
4    50
dtype: int64

El tercer elemento de la serie es: 30
La suma de todos los elementos de la serie es: 155

Serie s:
0    10
1    25
2    30
3    40
dtype: int64

# DataFrames
1. Crea un DataFrame llamado df con dos columnas: "A" con valores [1, 2, 3, 4, 5] y "B" con valores [10, 20, 30, 40, 50].
2. Muestra las primeras tres filas del DataFrame df.
3. Accede a la columna "B" del DataFrame df.
4. Calcula la media de la columna "B" en el DataFrame df.
5. Agrega una nueva columna llamada "C" al DataFrame df con valores [5, 10, 15, 20, 25]. Usa la función range.

In [3]:
# Crea un DataFrame llamado df con dos columnas: "A" con valores [1, 2, 3, 4, 5] y "B" con valores [10, 20, 30, 40, 50].
data = {"A": [1, 2, 3, 4, 5], "B": [10, 20, 30, 40, 50]}

df = pd.DataFrame(data)

# Muestra las primeras tres filas del DataFrame df.
print("Primeras tres filas del DataFrame", df[0:3], sep="\n")

# Accede a la columna "B" del DataFrame df.
print("\nColumna B del DataFrame", df["B"], sep="\n")

# Calcula la media de la columna "B" en el DataFrame df.
print("\nLa media de la columna B es:", df["B"].mean())

# Agrega una nueva columna llamada "C" al DataFrame df con valores [5, 10, 15, 20, 25].
# Usa la función range.
df["C"] = range(5, 30, 5)
print("\nDataFrame modificado", df, sep="\n")

Primeras tres filas del DataFrame
   A   B
0  1  10
1  2  20
2  3  30

Columna B del DataFrame
0    10
1    20
2    30
3    40
4    50
Name: B, dtype: int64

La media de la columna B es: 30.0

DataFrame modificado
   A   B   C
0  1  10   5
1  2  20  10
2  3  30  15
3  4  40  20
4  5  50  25

# Index
1. Crea una Serie llamada s con los valores [10, 20, 30, 40, 50] y asigna como índices las letras "a", "b", "c", "d", "e".
2. Imprime el índice de la Serie s.
3. Selecciona y muestra los elementos 'a', 'b' y 'c'.
4. Crea un DataFrame llamado df con dos columnas "A" y "B" y valores de [2, 4, 6, 8, 10] y [100, 200, 300, 400, 500]. Asigna como índices los nombres "Alice", "Bob", "Charlie", "David", "Emma".

In [4]:
# Crea una Serie llamada s con los valores [10, 20, 30, 40, 50] y asigna como índices las letras "a", "b", "c", "d", "e".
s = pd.Series([10, 20, 30, 40, 50], index=["a", "b", "c", "d", "e"])

# Imprime el índice de la Serie s.
print("El índice de la Serie s es:", s.index, sep="\n")

# Selecciona y muestra los elementos 'a', 'b' y 'c'.
print("\nLos elementos a, b y c son:", s.loc["a":"c"], sep="\n")

# Crea un DataFrame llamado df con dos columnas "A" y "B" y valores de [2, 4, 6, 8, 10]
# y [100, 200, 300, 400, 500]. Asigna como índices los nombres "Alice", "Bob", "Charlie", "David", "Emma".
data = {"A": [2, 4, 6, 8, 10], "B": [100, 200, 300, 400, 500]}
index = ["Alice", "Bob", "Charlie", "David", "Emma"]

df = pd.DataFrame(data, index)
print("\nDatos del nuevo DataFrame:", df, sep="\n")

El índice de la Serie s es:
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

Los elementos a, b y c son:
a    10
b    20
c    30
dtype: int64

Datos del nuevo DataFrame:
          A    B
Alice     2  100
Bob       4  200
Charlie   6  300
David     8  400
Emma     10  500

# Indexación y selección de datos
1. Selecciona la segunda fila del DataFrame df.
2. Selecciona la columna "A" del DataFrame df.
3. Selecciona las filas con índices "Alice" y "Charlie" del DataFrame df.
4. Elimina la columna 'A' y la fila 'Alice'. Imprime el dataframe resultante.

In [5]:
# Selecciona la segunda fila del DataFrame df.
print("Segunda fila del DataFrame:", df.iloc[1], sep="\n")

# Selecciona la columna "A" del DataFrame df.
print("\nColumna A del DataFrame:", df["A"], sep="\n")

# Selecciona las filas con índices "Alice" y "Charlie" del DataFrame df.
print("\nFilas Alice y Charlie del DataFrame:", df.loc[["Alice", "Charlie"]], sep="\n")

# Elimina la columna 'A' y la fila 'Alice'. Imprime el dataframe resultante.
df.drop(axis="columns", columns=["A"], inplace=True)
df.drop("Alice", inplace=True)

print("\nDataFrame luego de eliminar la columna A y la fila Alice:", df, sep="\n")

Segunda fila del DataFrame:
A      4
B    200
Name: Bob, dtype: int64

Columna A del DataFrame:
Alice       2
Bob         4
Charlie     6
David       8
Emma       10
Name: A, dtype: int64

Filas Alice y Charlie del DataFrame:
         A    B
Alice    2  100
Charlie  6  300

DataFrame luego de eliminar la columna A y la fila Alice:
           B
Bob      200
Charlie  300
David    400
Emma     500

# Manejo de datos faltantes

1. Dada la matriz df, reemplaza todos los valores nulos en el DataFrame df con ceros.

df = pd.DataFrame([[1, np.nan, np.nan],
                  [2,  3,      np.nan],
                   [np.nan, 4, 6]])
                   

2. Elimina todas las filas con valores nulos en el DataFrame df.

In [10]:
df = pd.DataFrame([[1, np.nan, np.nan], [2, 3, np.nan], [np.nan, 4, 6]])
print("\nDataFrame original", df, sep="\n")

# Dada la matriz df, reemplaza todos los valores nulos en el DataFrame df con ceros.
print("\nDataFrame con valores nulos reemplazados con ceros", df.fillna(0), sep="\n")

# Elimina todas las filas con valores nulos en el DataFrame df.
print("\nDataFrame con valores nulos eliminados", df.dropna(), sep="\n")

DataFrame original
     0    1    2
0  1.0  NaN  NaN
1  2.0  3.0  NaN
2  NaN  4.0  6.0

DataFrame con valores nulos reemplazados con ceros
     0    1    2
0  1.0  0.0  0.0
1  2.0  3.0  0.0
2  0.0  4.0  6.0

DataFrame con valores nulos eliminados
Empty DataFrame
Columns: [0, 1, 2]
Index: []

# Tipos de valores nulos

1. Verifica si hay valores nulos en el DataFrame df.
2. Cuenta el número de valores nulos en cada columna del DataFrame df.

In [18]:
# Verifica si hay valores nulos en el DataFrame df.
print("Valores nulos en el DataFrame", df.isnull(), sep="\n")

# Cuenta el número de valores nulos en cada columna del DataFrame df.
print("\nValores nulos en el DataFrame por columna", df.isnull().sum(), sep="\n")

Valores nulos en el DataFrame
       0      1      2
0  False   True   True
1  False  False   True
2   True  False  False

Valores nulos en el DataFrame por columna
0    1
1    1
2    2
dtype: int64

# PARTE 2

# Ejercicios:

1. Carga el conjunto de datos iris en un DataFrame llamado df.
2. Muestra las primeras cinco filas del DataFrame df.
3. Muestra la información sobre el DataFrame df, incluyendo el número de filas y columnas, y los tipos de datos de cada columna.
4. Muestra las columnas del DataFrame df.
5. Muestra los nombres de las columnas en formato de lista.
6. Selecciona la columna "sepal_length" del DataFrame df.
7. Selecciona las columnas "sepal_length" y "sepal_width" del DataFrame df.
8. Selecciona la primera fila del DataFrame df.
9. Selecciona las filas 10 a 20 del DataFrame df.
10. Filtra el DataFrame para mostrar solo las filas donde la columna "species" sea "setosa".
11. Verifica si hay valores nulos en el DataFrame df.
12. Elimina todas las filas con valores nulos en el DataFrame df.
13. Rellena los valores nulos en la columna "petal_width" con la media de esa columna en el DataFrame df.
14. Reemplaza todos los valores nulos en el DataFrame df con ceros.
15. Calcula la media de la columna "sepal_length" en el DataFrame df.
16. Calcula estadísticas resumidas para todo el DataFrame df.
17. Ordena el DataFrame df por los valores de la columna "sepal_length" en orden ascendente.
18. Ordena el DataFrame df por los valores de la columna "sepal_length" en orden descendente.
19. Selecciona las filas con índices 5 a 10 del DataFrame df.
20. Selecciona la tercera fila del DataFrame df.

In [26]:
# Carga el conjunto de datos iris en un DataFrame llamado df.
url = "https://raw.githubusercontent.com/NelbaBarreto/programacion-ciencias-datos/main/data/iris_dataset.csv"
df = pd.read_csv(url)

# Muestra las primeras cinco filas del DataFrame df.
print("Primeras cinco filas del DataFrame:", df.head(), sep="\n")

Primeras cinco filas del DataFrame:
   sepalLength  sepalWidth  petalLength  petalWidth species  species_code
0          5.1         3.5          1.4         0.2  setosa             0
1          4.9         3.0          1.4         0.2  setosa             0
2          4.7         3.2          1.3         0.2  setosa             0
3          4.6         3.1          1.5         0.2  setosa             0
4          5.0         3.6          1.4         0.2  setosa             0

In [27]:
# Muestra la información sobre el DataFrame df, incluyendo el número de filas y columnas, y los tipos de datos de cada columna.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepalLength   150 non-null    float64
 1   sepalWidth    150 non-null    float64
 2   petalLength   150 non-null    float64
 3   petalWidth    150 non-null    float64
 4   species       150 non-null    object
 5   species_code  150 non-null    int64
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [28]:
# Muestra las columnas del DataFrame df.
df.columns

Index(['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species',
       'species_code'],
      dtype='object')

In [29]:
# Muestra los nombres de las columnas en formato de lista.
print(list(df.columns))

['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species', 'species_code']

In [37]:
# Selecciona la columna "sepal_length" del DataFrame df.
print("Columna sepal_length del DataFrame:", df["sepalLength"], sep="\n")

Columna sepal_length del DataFrame:
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepalLength, Length: 150, dtype: float64

In [38]:
# Selecciona las columnas "sepal_length" y "sepal_width" del DataFrame df.
print("\nColumnas sepal_length y sepal_width del DataFrame:", df[["sepalLength", "sepalWidth"]], sep="\n")

Columnas sepal_length y sepal_width del DataFrame:
     sepalLength  sepalWidth
0            5.1         3.5
1            4.9         3.0
2            4.7         3.2
3            4.6         3.1
4            5.0         3.6
..           ...         ...
145          6.7         3.0
146          6.3         2.5
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

[150 rows x 2 columns]

In [39]:
# Selecciona la primera fila del DataFrame df.
print("\nPrimera fila del DataFrame:", df.iloc[0], sep="\n")

Primera fila del DataFrame:
sepalLength        5.1
sepalWidth         3.5
petalLength        1.4
petalWidth         0.2
species         setosa
species_code         0
Name: 0, dtype: object

In [40]:
# Selecciona las filas 10 a 20 del DataFrame df.
print("\nFilas del 10 al 20 del DataFrame:", df.iloc[10:21], sep="\n")

Filas del 10 al 20 del DataFrame:
    sepalLength  sepalWidth  petalLength  petalWidth species  species_code
10          5.4         3.7          1.5         0.2  setosa             0
11          4.8         3.4          1.6         0.2  setosa             0
12          4.8         3.0          1.4         0.1  setosa             0
13          4.3         3.0          1.1         0.1  setosa             0
14          5.8         4.0          1.2         0.2  setosa             0
15          5.7         4.4          1.5         0.4  setosa             0
16          5.4         3.9          1.3         0.4  setosa             0
17          5.1         3.5          1.4         0.3  setosa             0
18          5.7         3.8          1.7         0.3  setosa             0
19          5.1         3.8          1.5         0.3  setosa             0
20          5.4         3.4          1.7         0.2  setosa             0

In [41]:
# Filtra el DataFrame para mostrar solo las filas donde la columna "species" sea "setosa".
print("\nFilas donde la columna species es setosa:", df[df.species == "setosa"], sep="\n")

Filas donde la columna species es setosa:
    sepalLength  sepalWidth  petalLength  petalWidth species  species_code
0           5.1         3.5          1.4         0.2  setosa             0
1           4.9         3.0          1.4         0.2  setosa             0
2           4.7         3.2          1.3         0.2  setosa             0
3           4.6         3.1          1.5         0.2  setosa             0
4           5.0         3.6          1.4         0.2  setosa             0
5           5.4         3.9          1.7         0.4  setosa             0
6           4.6         3.4          1.4         0.3  setosa             0
7           5.0         3.4          1.5         0.2  setosa             0
8           4.4         2.9          1.4         0.2  setosa             0
9           4.9         3.1          1.5         0.1  setosa             0
10          5.4         3.7          1.5         0.2  setosa             0
11          4.8         3.4          1.6         0.2  setosa             0
12          4.8         3.0          1.4         0.1  setosa             0
13          4.3         3.0          1.1         0.1  setosa             0
14          5.8         4.0          1.2         0.2  setosa             0
15          5.7         4.4          1.5         0.4  setosa             0
16          5.4         3.9          1.3         0.4  setosa             0
17          5.1         3.5          1.4         0.3  setosa             0
18          5.7         3.8          1.7         0.3  setosa             0
19          5.1         3.8          1.5         0.3  setosa             0
20          5.4         3.4          1.7         0.2  setosa             0
21          5.1         3.7          1.5         0.4  setosa             0
22          4.6         3.6          1.0         0.2  setosa             0
23          5.1         3.3          1.7         0.5  setosa             0
24          4.8         3.4          1.9         0.2  setosa             0
25          5.0         3.0          1.6         0.2  setosa             0
26          5.0         3.4          1.6         0.4  setosa             0
27          5.2         3.5          1.5         0.2  setosa             0
28          5.2         3.4          1.4         0.2  setosa             0
29          4.7         3.2          1.6         0.2  setosa             0
30          4.8         3.1          1.6         0.2  setosa             0
31          5.4         3.4          1.5         0.4  setosa             0
32          5.2         4.1          1.5         0.1  setosa             0
33          5.5         4.2          1.4         0.2  setosa             0
34          4.9         3.1          1.5         0.2  setosa             0
35          5.0         3.2          1.2         0.2  setosa             0
36          5.5         3.5          1.3         0.2  setosa             0
37          4.9         3.6          1.4         0.1  setosa             0
38          4.4         3.0          1.3         0.2  setosa             0
39          5.1         3.4          1.5         0.2  setosa             0
40          5.0         3.5          1.3         0.3  setosa             0
41          4.5         2.3          1.3         0.3  setosa             0
42          4.4         3.2          1.3         0.2  setosa             0
43          5.0         3.5          1.6         0.6  setosa             0
44          5.1         3.8          1.9         0.4  setosa             0
45          4.8         3.0          1.4         0.3  setosa             0
46          5.1         3.8          1.6         0.2  setosa             0
47          4.6         3.2          1.4         0.2  setosa             0
48          5.3         3.7          1.5         0.2  setosa             0
49          5.0         3.3          1.4         0.2  setosa             0

In [43]:
# Verifica si hay valores nulos en el DataFrame df.
print("Valores nulos en el DataFrame", df.isnull().sum(), sep="\n")

Valores nulos en el DataFrame
sepalLength     0
sepalWidth      0
petalLength     0
petalWidth      0
species         0
species_code    0
dtype: int64

In [45]:
# Elimina todas las filas con valores nulos en el DataFrame df.
df.dropna()

     sepalLength  sepalWidth  petalLength  petalWidth    species  species_code
0            5.1         3.5          1.4         0.2     setosa             0
1            4.9         3.0          1.4         0.2     setosa             0
2            4.7         3.2          1.3         0.2     setosa             0
3            4.6         3.1          1.5         0.2     setosa             0
4            5.0         3.6          1.4         0.2     setosa             0
..           ...         ...          ...         ...        ...           ...
145          6.7         3.0          5.2         2.3  virginica             2
146          6.3         2.5          5.0         1.9  virginica             2
147          6.5         3.0          5.2         2.0  virginica             2
148          6.2         3.4          5.4         2.3  virginica             2
149          5.9         3.0          5.1         1.8  virginica             2

[150 rows x 6 columns]

In [47]:
# Rellena los valores nulos en la columna "petal_width" con la media de esa columna en el DataFrame df.
petal_width_mean = df["petalWidth"].mean()
print("Media de la columna petal_width", petal_width_mean)

# Rellenar los valores nulos en la columna 1 con la media calculada
df["petalWidth"].fillna(petal_width_mean)

Media de la columna petal_width 1.1993333333333338

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petalWidth, Length: 150, dtype: float64

In [48]:
# Reemplaza todos los valores nulos en el DataFrame df con ceros.
df.fillna(0)

     sepalLength  sepalWidth  petalLength  petalWidth    species  species_code
0            5.1         3.5          1.4         0.2     setosa             0
1            4.9         3.0          1.4         0.2     setosa             0
2            4.7         3.2          1.3         0.2     setosa             0
3            4.6         3.1          1.5         0.2     setosa             0
4            5.0         3.6          1.4         0.2     setosa             0
..           ...         ...          ...         ...        ...           ...
145          6.7         3.0          5.2         2.3  virginica             2
146          6.3         2.5          5.0         1.9  virginica             2
147          6.5         3.0          5.2         2.0  virginica             2
148          6.2         3.4          5.4         2.3  virginica             2
149          5.9         3.0          5.1         1.8  virginica             2

[150 rows x 6 columns]

In [49]:
# Calcula la media de la columna "sepal_length" en el DataFrame df.
sepal_length_mean = df["sepalLength"].mean()
print("Media de la columna sepal_length", sepal_length_mean)

Media de la columna sepal_length 5.843333333333334

In [50]:
# Calcula estadísticas resumidas para todo el DataFrame df.
df.describe()

       sepalLength  sepalWidth  petalLength  petalWidth  species_code
count   150.000000  150.000000   150.000000  150.000000    150.000000
mean      5.843333    3.057333     3.758000    1.199333      1.000000
std       0.828066    0.435866     1.765298    0.762238      0.819232
min       4.300000    2.000000     1.000000    0.100000      0.000000
25%       5.100000    2.800000     1.600000    0.300000      0.000000
50%       5.800000    3.000000     4.350000    1.300000      1.000000
75%       6.400000    3.300000     5.100000    1.800000      2.000000
max       7.900000    4.400000     6.900000    2.500000      2.000000

In [51]:
# Ordena el DataFrame df por los valores de la columna "sepal_length" en orden ascendente.
df.sort_values(by=["sepalLength"])

     sepalLength  sepalWidth  petalLength  petalWidth    species  species_code
13           4.3         3.0          1.1         0.1     setosa             0
42           4.4         3.2          1.3         0.2     setosa             0
38           4.4         3.0          1.3         0.2     setosa             0
8            4.4         2.9          1.4         0.2     setosa             0
41           4.5         2.3          1.3         0.3     setosa             0
..           ...         ...          ...         ...        ...           ...
122          7.7         2.8          6.7         2.0  virginica             2
118          7.7         2.6          6.9         2.3  virginica             2
117          7.7         3.8          6.7         2.2  virginica             2
135          7.7         3.0          6.1         2.3  virginica             2
131          7.9         3.8          6.4         2.0  virginica             2

[150 rows x 6 columns]

In [52]:
# Ordena el DataFrame df por los valores de la columna "sepal_length" en orden descendente.
df.sort_values(by=["sepalLength"], ascending=False)

     sepalLength  sepalWidth  petalLength  petalWidth    species  species_code
131          7.9         3.8          6.4         2.0  virginica             2
135          7.7         3.0          6.1         2.3  virginica             2
122          7.7         2.8          6.7         2.0  virginica             2
117          7.7         3.8          6.7         2.2  virginica             2
118          7.7         2.6          6.9         2.3  virginica             2
..           ...         ...          ...         ...        ...           ...
41           4.5         2.3          1.3         0.3     setosa             0
42           4.4         3.2          1.3         0.2     setosa             0
38           4.4         3.0          1.3         0.2     setosa             0
8            4.4         2.9          1.4         0.2     setosa             0
13           4.3         3.0          1.1         0.1     setosa             0

[150 rows x 6 columns]

In [54]:
# Selecciona las filas con índices 5 a 10 del DataFrame df.
df.loc[5:10]

    sepalLength  sepalWidth  petalLength  petalWidth species  species_code
5           5.4         3.9          1.7         0.4  setosa             0
6           4.6         3.4          1.4         0.3  setosa             0
7           5.0         3.4          1.5         0.2  setosa             0
8           4.4         2.9          1.4         0.2  setosa             0
9           4.9         3.1          1.5         0.1  setosa             0
10          5.4         3.7          1.5         0.2  setosa             0

In [58]:
# Selecciona la tercera fila del DataFrame df.
df.iloc[2]

sepalLength        4.7
sepalWidth         3.2
petalLength        1.3
petalWidth         0.2
species         setosa
species_code         0
Name: 2, dtype: object